
DROP TABLE IF EXISTS Alert;
DROP TABLE IF EXISTS Device;
DROP TABLE IF EXISTS DeviceType;
DROP TABLE IF EXISTS UserRoleAssoc;
DROP TABLE IF EXISTS Role;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Setting;

CREATE TABLE Setting (
  id        INTEGER PRIMARY KEY AUTOINCREMENT,
  param     TEXT UNIQUE,
  value     TEXT
);

CREATE TABLE User (
  id        INTEGER PRIMARY KEY AUTOINCREMENT,
  name      TEXT NOT NULL,
  userid    TEXT NOT NULL,
  passwd    TEXT NOT NULL,
  active    INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE Role (
  id        TEXT NOT NULL PRIMARY KEY,
  name      TEXT NOT NULL
);

CREATE TABLE UserRoleAssoc (
  user_id   INTEGER NOT NULL,
  role_id   TEXT NOT NULL,
  PRIMARY KEY (user_id, role_id),
  FOREIGN KEY (user_id) REFERENCES User (id) ON DELETE CASCADE,
  FOREIGN KEY (role_id) REFERENCES Role (id) ON DELETE CASCADE
);

CREATE TABLE DeviceType (
  id        INTEGER NOT NULL PRIMARY KEY,
  name      TEXT NOT NULL,
  driver    TEXT NOT NULL
);

CREATE TABLE Device (
  id        INTEGER PRIMARY KEY AUTOINCREMENT,
  name      TEXT NOT NULL,
  address   INTEGER NOT NULL,
  type_id   INTEGER NOT NULL,
  FOREIGN KEY (type_id) REFERENCES DeviceType (id)
);

CREATE TABLE Alert (
  id        INTEGER PRIMARY KEY AUTOINCREMENT,
  device_id INTEGER,
  severity  INTEGER,
  message   TEXT NOT NULL,
  cleared   INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (device_id) REFERENCES Device (id) ON DELETE CASCADE
);
